### ISSUE TITLE
Binding crashes on Openhab2 RC1-1

### ISSUE THREAD

**Issue by mawa85** [octa22/org.openhab.binding.xiaomigateway#4]
After a few events  the binding (snapshot6) crashes on the current OH2 RC. I had no issues with beta4 before.
I can't see any errors in the openhab.log but the service status shows something

> root@server:~# service openhab2 status
> ● openhab2.service - openHAB 2 - empowering the smart home
>    Loaded: loaded (/usr/lib/systemd/system/openhab2.service; disabled; vendor preset: enabled)
>    Active: active (running) since Do 2017-01-19 19:56:15 CET; 5min ago
>      Docs: http://docs.openhab.org
>            https://community.openhab.org
>   Process: 3322 ExecStop=/usr/share/openhab2/runtime/bin/stop (code=exited, status=0/SUCCESS)
>  Main PID: 3562 (karaf)
>     Tasks: 144
>    Memory: 789.1M
>       CPU: 1min 1.767s
>    CGroup: /system.slice/openhab2.service
>            ├─3562 /bin/bash /usr/share/openhab2/runtime/bin/karaf server
>            └─3737 /usr/bin/java -Dopenhab.home=/usr/share/openhab2 -Dopenhab.conf=/etc/openhab2 -Dopenhab.runtime=/usr/share/openhab2/runtime -Dopenhab.userd
> 
> Jan 19 19:56:15 server systemd[1]: Started openHAB 2 - empowering the smart home.
> Jan 19 19:56:15 server start.sh[3562]: Launching the openHAB runtime...
> Jan 19 20:01:29 server start.sh[3562]: Exception in thread "Thread-52" java.lang.NullPointerException
> Jan 19 20:01:29 server start.sh[3562]:         at org.openhab.binding.xiaomigateway.internal.XiaomiGatewayBinding.processMotionEvent(XiaomiGatewayBinding.jav
> Jan 19 20:01:29 server start.sh[3562]:         at org.openhab.binding.xiaomigateway.internal.XiaomiGatewayBinding.processOtherCommands(XiaomiGatewayBinding.j
> Jan 19 20:01:29 server start.sh[3562]:         at org.openhab.binding.xiaomigateway.internal.XiaomiGatewayBinding.receiveData(XiaomiGatewayBinding.java:208)
> Jan 19 20:01:29 server start.sh[3562]:         at org.openhab.binding.xiaomigateway.internal.XiaomiGatewayBinding.access$1(XiaomiGatewayBinding.java:169)
> Jan 19 20:01:29 server start.sh[3562]:         at org.openhab.binding.xiaomigateway.internal.XiaomiGatewayBinding$1.run(XiaomiGatewayBinding.java:163)
> Jan 19 20:01:29 server start.sh[3562]:         at java.lang.Thread.run(Thread.java:745)
>

**Comment by octa22** [comment]
Do you have the received data which caused the NullPointerException? It seems it has received other motion data than expected. Logger logs all received packets using info so it must be logged somewhere...

**Comment by octa22** [comment]
Could you please test this binding? https://dl.dropboxusercontent.com/u/34515980/org.openhab.binding.xiaomigateway-1.9.0-SNAPSHOT.jar

I guess the motion sensor sends undocumented heartbeat and this contains the fix...

**Comment by mawa85** [comment]
Thanks for your help.
I just could do a short test, the binding did not crash anymore, but I also did not receive a motion CLOSED event on the item. I'm not at home till sunday evening, so I can continue testing on monday.

**Comment by octa22** [comment]
OK thanks. If you can paste here the heartbeat packet it receives from a motion sensor, it would help a lot.

**Comment by mawa85** [comment]
hope that helps:

> 2017-01-22 16:12:24.975 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"read_ack","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"no_motion\"}"}
2017-01-22 16:39:38.278 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"heartbeat","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"no_motion\"}"}
2017-01-22 17:34:41.191 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"heartbeat","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"no_motion\"}"}
2017-01-22 18:29:42.159 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"heartbeat","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"no_motion\"}"}
2017-01-22 18:47:41.945 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:48:42.216 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:50:41.956 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"no_motion\":\"120\"}"}
2017-01-22 18:51:01.376 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:52:09.613 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:53:25.906 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:54:29.220 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:55:30.504 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:56:33.326 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:57:36.278 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:58:45.173 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 18:59:46.168 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 19:01:13.085 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 19:03:12.834 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"no_motion\":\"120\"}"}
2017-01-22 19:03:41.546 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 19:04:43.479 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"status\":\"motion\"}"}
2017-01-22 19:06:43.224 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"no_motion\":\"120\"}"}
2017-01-22 19:07:43.089 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"no_motion\":\"180\"}"}
2017-01-22 19:09:42.822 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"report","model":"motion","sid":"158d00010e46ea","short_id":22751,"data":"{\"no_motion\":\"300\"}"}

**Comment by octa22** [comment]
Thank you very much, I think I have found it - can you please test this version?
https://dl.dropboxusercontent.com/u/34515980/org.openhab.binding.xiaomigateway-1.9.0-SNAPSHOT.jar

**Comment by mawa85** [comment]
Seems to work good now, thanks a lot !

event log
`2017-01-22 21:15:54.322 [ItemStateChangedEvent     ] - XiaomiMotion changed from OPEN to CLOSED
2017-01-22 21:22:32.075 [ItemStateChangedEvent     ] - XiaomiMotion changed from CLOSED to OPEN
2017-01-22 21:24:31.798 [ItemStateChangedEvent     ] - XiaomiMotion changed from OPEN to CLOSED
2017-01-22 21:28:00.396 [ItemStateChangedEvent     ] - XiaomiMotion changed from CLOSED to OPEN
2017-01-22 21:30:00.105 [ItemStateChangedEvent     ] - XiaomiMotion changed from OPEN to CLOSED
2017-01-22 21:54:20.221 [ItemStateChangedEvent     ] - XiaomiMotion changed from CLOSED to OPEN
2017-01-22 21:56:19.949 [ItemStateChangedEvent     ] - XiaomiMotion changed from OPEN to CLOSED
2017-01-22 22:06:53.864 [ItemStateChangedEvent     ] - XiaomiMotion changed from CLOSED to OPEN
`
